import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10 },
  header: { textAlign: 'center', marginBottom: 20, borderBottom: '2 solid #1e3a5f', paddingBottom: 10 },
  title: { fontSize: 20, fontWeight: 'bold', color: '#1e3a5f' },
  subtitle: { fontSize: 10, color: '#666', marginTop: 4 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', color: '#1e3a5f', marginTop: 16, marginBottom: 8, paddingBottom: 4, borderBottom: '1 solid #ddd' },
  row: { flexDirection: 'row', paddingVertical: 4, borderBottom: '1 solid #eee' },
  cell: { flex: 1 },
  cellRight: { flex: 1, textAlign: 'right' },
  bold: { fontWeight: 'bold' },
  total: { flexDirection: 'row', paddingVertical: 6, borderTop: '2 solid #1e3a5f', marginTop: 4 },
  green: { color: '#16a34a' },
  red: { color: '#dc2626' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#999', borderTop: '1 solid #ddd', paddingTop: 8 },
});

interface ReportPDFProps {
  title: string;
  subtitle?: string;
  children: React.ReactNode;
}

export const ReportPDF = ({ title, subtitle, children }: ReportPDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>PrimeLedger</Text>
        <Text style={styles.subtitle}>{title}</Text>
        {subtitle && <Text style={styles.subtitle}>{subtitle}</Text>}
      </View>
      {children}
      <View style={styles.footer}>
        <Text>Generated by PrimeLedger on {new Date().toLocaleDateString()}</Text>
      </View>
    </Page>
  </Document>
);

export const PDFRow = ({ label, value, bold }: { label: string; value: string; bold?: boolean }) => (
  <View style={styles.row}>
    <Text style={bold ? { fontWeight: 'bold' } : {}}>{label}</Text>
    <Text style={bold ? { ...styles.cellRight, fontWeight: 'bold' } : styles.cellRight}>{value}</Text>
  </View>
);

export const PDFTotal = ({ label, value }: { label: string; value: string }) => (
  <View style={styles.total}>
    <Text style={[styles.cell, styles.bold]}>{label}</Text>
    <Text style={[styles.cellRight, styles.bold]}>{value}</Text>
  </View>
);